In [1]:
## imports here !!!
import numpy as np
import pandas as pd
import xgboost as xgb
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats

from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import accuracy_score

from sklearn.impute import SimpleImputer

import random
random.seed(95)

'''
Description : 
'''

Random Forest

Normalising data...
Feature 17 18 19 are dropped since majority is unfilled..
Grid Search CV : 10 steps

Imputed missing valuess through mean..
Removed outliers wrt data other than target variable..

Best params..

{'colsample_bytree': 0.8, 'gamma': 0.5, 'max_depth': 5, 'min_child_weight': 1, 'subsample': 0.8}
accuracy_score 90.9090909090909



L1--> imputed
L2--> dropping
L3 --> removing outliers

In [2]:
'''
Importing data
'''
train_data= pd.read_csv('iith_foml_2020_train.csv')
train = pd.DataFrame(train_data)   ### Raw data
test_data= pd.read_csv('iith_foml_2020_test.csv')
test = pd.DataFrame(test_data)    ### Raw data
test.head()



#test.describe()

,Feature 1 (Discrete),Feature 2 (Discrete),Feature 3 (Discrete),Feature 4 (Discrete),Feature 5 (Discrete),Feature 6 (Discrete),Feature 7 (Discrete),Feature 8 (Discrete),Feature 9,Feature 10,...,Feature 15,Feature 16,Feature 17,Feature 18,Feature 19 (Discrete),Feature 20 (Discrete),Feature 21 (Discrete),Feature 22 (Discrete),Feature 23 (Discrete),Feature 24
0,146,12,42,14,7,1,1,1,118.004,35693.5,...,4200.3,1900.1,NaN,NaN,44,12,2,42,146,37384.5
1,35,0,12,5,0,0,1,0,0.001,471.5,...,531.4,NaN,NaN,NaN,17,6,8,0,35,41465.1
2,1018,8,259,2,1,1,1,1,NaN,35774.5,...,5514.2,NaN,NaN,15.04,1,1,3,20,1018,37826.2
3,383,7,117,5,1,1,1,1,53.002,34094.1,...,3358.4,1100.2,14000.001,15.04,101,6,3,20,383,40277.3
4,1216,7,40,5,2,0,1,4,0.005,1471.3,...,225.1,NaN,NaN,3.02,276,6,7,43,1221,28419.5

### Analysis of missing values...

In [3]:

def Summarise_missing_values(new_data):
    cols_with_missing = (col for col in new_data.columns if new_data[col].isnull().any())
    num_missing = (new_data[cols_with_missing].isnull()).sum()
    print("Missing values in percent")
    # report the results
    print(round((num_missing/new_data.shape[0]) * 100, 2))
    print("######################################################################################") 

print("****************************For TRAIN data")
Summarise_missing_values(train.copy())
print("****************************For Test data")
Summarise_missing_values(test.copy())

****************************For TRAIN data
Missing values in percent
Feature 9      1.41
Feature 10     0.10
Feature 11     0.10
Feature 12     0.10
Feature 13     0.10
Feature 14     0.10
Feature 15     7.24
Feature 16    67.30
Feature 17    54.93
Feature 18    33.20
Feature 24     0.10
dtype: float64
######################################################################################
****************************For Test data
Missing values in percent
Feature 9      0.94
Feature 14     0.47
Feature 15     7.28
Feature 16    65.49
Feature 17    52.82
Feature 18    26.76
dtype: float64
######################################################################################

###  Filling missing values by imputation through mean...

In [4]:

def imputing_missing_values(df):
    data = df.to_numpy()
    # define the imputer
    imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
    imputer  = imputer.fit(data)
    # transform the dataset
    transformed_values = imputer.transform(data)
    imputed_data = pd.DataFrame(data = transformed_values,columns = df.columns) 
    return imputed_data


L1_train = imputing_missing_values(train)
L1_test = imputing_missing_values(test)

pd.set_option('display.float_format', lambda x: '%.3f' % x)
pd.set_option('display.max_columns', None)
L1_train.describe()
#imputed_test.describe()

,Feature 1 (Discrete),Feature 2 (Discrete),Feature 3 (Discrete),Feature 4 (Discrete),Feature 5 (Discrete),Feature 6 (Discrete),Feature 7 (Discrete),Feature 8 (Discrete),Feature 9,Feature 10,Feature 11,Feature 12,Feature 13,Feature 14,Feature 15,Feature 16,Feature 17,Feature 18,Feature 19 (Discrete),Feature 20 (Discrete),Feature 21 (Discrete),Feature 22 (Discrete),Feature 23 (Discrete),Feature 24,Target Variable (Discrete)
count,994.000,994.000,994.000,994.000,994.000,994.000,994.000,994.000,994.000,994.000,994.000,994.000,994.000,994.000,994.000,994.000,994.000,994.000,994.000,994.000,994.000,994.000,994.000,994.000,994.000
mean,708.187,5.899,159.564,11.651,2.624,0.581,2.041,1.643,6.113,14527.974,16057.137,0.020,50.015,642.128,2042.520,1329.780,3814.421,2061.807,94.004,7.660,4.777,45.635,709.334,34605.373,1.706
std,405.826,7.563,106.706,15.159,2.652,0.747,2.550,1.532,54.273,16438.642,18967.035,0.111,41.766,659.089,2201.290,722.723,3117.065,7582.518,90.311,10.658,4.774,36.070,407.361,6117.763,2.417
min,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,-177.116,200.400,322.500,0.000,0.001,7.014,0.200,6.500,4.055,0.270,0.000,0.000,0.000,0.000,0.000,7530.300,0.000
25%,357.750,0.000,66.250,2.000,1.000,0.000,1.000,0.000,0.001,621.300,683.775,0.000,0.094,97.702,207.150,1329.780,1615.004,8.030,12.000,1.000,1.000,14.250,357.750,28378.375,0.250
50%,705.000,3.000,146.000,5.000,2.000,0.000,1.000,1.000,0.003,1409.200,1415.150,0.001,54.904,114.101,1480.450,1329.780,3814.421,15.020,73.500,2.000,3.000,39.000,705.000,37264.750,1.000
75%,1064.500,8.000,239.000,15.000,3.000,1.000,1.000,3.000,0.005,35770.400,35794.500,0.002,97.470,1436.083,3200.375,1329.780,3814.421,2061.807,152.000,12.000,7.000,64.000,1064.500,40038.150,2.000
max,1412.000,46.000,386.000,80.000,14.000,4.000,19.000,7.000,328.502,37778.400,156833.300,0.864,143.402,4032.863,18000.300,10000.400,20000.005,44118.010,318.000,58.000,23.000,155.000,1417.000,41634.300,17.000

### Normalising data : Min-max

In [6]:
def normalize(df):
    result = df.copy()
    for feature_name in df.columns:
        max_value = df[feature_name].max()
        min_value = df[feature_name].min()
        result[feature_name] = (df[feature_name] - min_value) / (max_value - min_value)
    return result

### Remove outliers..

In [5]:
#### Removing outliers..


def remove_outliers(df,r = 6):
    outfree = pd.DataFrame()
    outfree = df[(np.abs(stats.zscore(df.drop(columns=['Target Variable (Discrete)'],axis = 1))) < r).all(axis=1)]
    outfree.index = range(len(outfree))
    return outfree

In [6]:
'''
Dividing into X, Y
'''


L2_train = L1_train.drop(columns=['Feature 16', 'Feature 17','Feature 18'],axis = 1)
L2_test = L1_test.drop(columns=['Feature 16', 'Feature 17','Feature 18'],axis = 1)

L3_train = L2_train   #### Add remove outliers here to do
L3_test = L2_test


#################################################################################

X = L3_train.drop(columns=['Target Variable (Discrete)'],axis = 1)
Y = L3_train[['Target Variable (Discrete)']]
X_test = L3_test

print(train.shape)
print(X.shape)
Y.describe()

#Summarise_missing_values(Y.copy())
### Normalising...
#X = normalize(X)
#X_test = normalize(X_test)

(994, 25)
(994, 21)

       Target Variable (Discrete)
count                     994.000
mean                        1.706
std                         2.417
min                         0.000
25%                         0.250
50%                         1.000
75%                         2.000
max                        17.000

In [7]:
L3_train.tail()

,Feature 1 (Discrete),Feature 2 (Discrete),Feature 3 (Discrete),Feature 4 (Discrete),Feature 5 (Discrete),Feature 6 (Discrete),Feature 7 (Discrete),Feature 8 (Discrete),Feature 9,Feature 10,Feature 11,Feature 12,Feature 13,Feature 14,Feature 15,Feature 19 (Discrete),Feature 20 (Discrete),Feature 21 (Discrete),Feature 22 (Discrete),Feature 23 (Discrete),Feature 24,Target Variable (Discrete)
989,1388.000,0.000,382.000,14.000,2.000,0.000,1.000,0.000,0.002,628.500,656.500,0.002,98.072,97.574,2700.400,104.000,12.000,11.000,53.000,1393.000,41473.400,0.000
990,1339.000,0.000,344.000,14.000,3.000,0.000,1.000,0.000,0.002,520.300,540.300,0.001,97.462,95.235,1.300,205.000,12.000,10.000,63.000,1344.000,40916.200,2.000
991,527.000,7.000,40.000,5.000,5.000,2.000,1.000,3.000,0.005,19130.100,19162.400,0.001,64.825,676.384,1415.500,101.000,6.000,7.000,95.000,527.000,37938.400,6.000
992,1144.000,12.000,120.000,14.000,3.000,0.000,1.000,0.000,0.003,785.200,803.300,0.001,98.503,100.805,300.100,166.000,12.000,11.000,53.000,1149.000,33433.500,0.000
993,1284.000,0.000,346.000,14.000,0.000,0.000,1.000,0.000,0.002,466.300,485.500,0.001,97.322,94.105,3.300,289.000,12.000,11.000,134.000,1289.000,40927.100,2.000

In [20]:

'''
Training with stratified K-fold with random forest
'''

i=1

splits = 10
kf = StratifiedKFold(n_splits= splits,random_state=1,shuffle=True)



accuracy = [0]* splits
for train_index,test_index in kf.split(X,Y):
    print('\n{} of kfold {}'.format(i,kf.n_splits))
    xtr,xvl = X.loc[train_index],X.loc[test_index]
    ytr,yvl = Y.loc[train_index],Y.loc[test_index]

    model = RandomForestClassifier(n_estimators=100, bootstrap = True,max_features = 'sqrt')
    model.fit(xtr, ytr)

    #print (model.best_params_)
    y_pred=model.predict(xvl)
    y_pred = [round(value) for value in y_pred]
    
    
    print('accuracy_score',accuracy_score(yvl,y_pred) * 100)
    accuracy[i-1] = accuracy_score(yvl,y_pred) * 100
    i+=1

print("Summarising resultss...")
print(np.mean(accuracy))

/home/surya/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py:667: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=10.
  % (min_groups, self.n_splits)), UserWarning)
/home/surya/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:19: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

1 of kfold 10
accuracy_score 92.0

2 of kfold 10

/home/surya/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:19: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

accuracy_score 91.0

3 of kfold 10

/home/surya/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:19: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

accuracy_score 89.0

4 of kfold 10

/home/surya/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:19: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

accuracy_score 90.0

5 of kfold 10

/home/surya/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:19: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

accuracy_score 88.88888888888889

6 of kfold 10

/home/surya/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:19: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

accuracy_score 94.94949494949495

7 of kfold 10

/home/surya/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:19: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

accuracy_score 88.88888888888889

8 of kfold 10

/home/surya/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:19: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

accuracy_score 89.8989898989899

9 of kfold 10

/home/surya/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:19: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

accuracy_score 91.91919191919192

10 of kfold 10

/home/surya/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:19: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

accuracy_score 90.9090909090909
Summarising resultss...
90.74545454545454

In [14]:
def predict_and_submission(test_data,model,title):### test_data in pd format
    test = pd.DataFrame(test_data)
    predictions = model.predict(test)

    output_test_data = pd.DataFrame() 
    output_test_data['Category'] = predictions.astype(int)

    output_test_data['Id'] = list(np.arange(1,predictions.size+1))

    submission = output_test_data[['Id','Category']]
    submission.to_csv(title, index=False)
    submission.head()
    return submission

##### Plsss change the title........
output = predict_and_submission(X_test,model,title = "S_010.csv")
output.head()

   Id  Category
0   1         6
1   2         2
2   3         1
3   4         1
4   5         1

In [25]:
def same_preds_count(BEST, present):
    df = present.loc[present['Category'] != BEST['Category']]
    return df.count()
    
best1 = pd.DataFrame( pd.read_csv('S_001.csv') )
best2 = pd.DataFrame( pd.read_csv('S_010.csv') )


print(same_preds_count(best1,best2))

Id          27
Category    27
dtype: int64

In [30]:
a = str('asdf')
b = str('f')
print(a - b)

TypeError: unsupported operand type(s) for -: 'str' and 'str'

### Mojority vote

In [49]:
print(len(majority_vote["Ensemble"]))

426

In [67]:
def generate_majoriy_vote(df_list,title):
    
    Majority_vote = pd.DataFrame()
    df = pd.DataFrame( pd.read_csv(df_list[0]) )
    Majority_vote['Id'] = df['Id']
    
    for i in range(len(df_list)):
        df = pd.DataFrame( pd.read_csv(df_list[i]) )
        Majority_vote[df_list[i]] = df['Category']
        
    Majority_vote["Ensemble"] = Majority_vote.mode(axis=1)[0].astype(int)
    

    ### Creating ensemble submission
    submission = pd.DataFrame() 
    
    submission['Id'] = Majority_vote ['Id']
    submission['Category'] = Majority_vote["Ensemble"]
    

    ### Creating csv
    #submission = output_test_data[['Id','Category']]
    submission.to_csv(title, index=False)    
        
    return Majority_vote

df_list = ['S_001.csv','S_003.csv','S_010.csv']
Majority = generate_majoriy_vote( df_list, "Ensemble_1_3_10.csv" )
Majority

      Id  S_001.csv  S_003.csv  S_010.csv  Ensemble
0      1          6          6          6         6
1      2          2          0          2         2
2      3          1          1          1         1
3      4          1          1          1         1
4      5          1          1          1         1
5      6          2          2          2         2
6      7          1          1          1         1
7      8          5          5          5         5
8      9          5          5          5         5
9     10          0          0          0         0
10    11          1          1          1         1
11    12          6          6          6         6
12    13          0          0          0         0
13    14          1          1          1         1
14    15          1          2          2         2
15    16          0          0          0         0
16    17          2          1          2         2
17    18          1          1          1         1
18    19          1          1          1         1
19    20          1          1          1         1
20    21          5          5          5         5
21    22          1          1          2         1
22    23          1          1          1         1
23    24          1          1          1         1
24    25          0          0          0         0
25    26          0          0          0         0
26    27          6          6          6         6
27    28          0          0          0         0
28    29          1          1          1         1
29    30          0          0          0         0
30    31          0          0         13         0
31    32          1          1          1         1
32    33          1          1          1         1
33    34          6          6          6         6
34    35          1          1          1         1
35    36          0          0          0         0
36    37          6          6          6         6
37    38          0          0          0         0
38    39          0          0          0         0
39    40          1          1          1         1
40    41          2          5          1         1
41    42          1          1          1         1
42    43          1          1          1         1
43    44          1          1          1         1
44    45          0          0          0         0
45    46          1          1          4         1
46    47          1          1          1         1
47    48          0          0          0         0
48    49          6          6          6         6
49    50          1          1          1         1
50    51          2          2          2         2
51    52          1          1          1         1
52    53          1          1          1         1
53    54          1          1          1         1
54    55          1          1          1         1
55    56          1          1          1         1
56    57          6          6          6         6
57    58          2          2          2         2
58    59          0          0          0         0
59    60          0          0          0         0
60    61          1          1          1         1
61    62          1          1          1         1
62    63          1          1          1         1
63    64          6          6          6         6
64    65          1          1          1         1
65    66          1          1          1         1
66    67          2          2          2         2
67    68          2          2          2         2
68    69          1          1          1         1
69    70          2          2          2         2
70    71          1          1          1         1
71    72          2          2          2         2
72    73          1          1          1         1
73    74          1          1          1         1
74    75          6          6          6         6
75    76          1          1          1         1
76    77          1          1          1         1
77    78          1          1          1         1
78    79          1          1          1         1
79    80          1          1          1         1
80    81          1          5          5         5
81    82          1          1          1         1
82    83          0          0          0         0
83    84          1          4          4         4
84    85          6          6          6         6
85    86          0          0          0         0
86    87          1          1          1         1
87    88          1          1          1         1
88    89          1          1          1         1
89    90          1          1          1         1
90    91          1          1          1         1
91    92          0          0          0         0
92    93          2          2          2         2
93    94          1          1          1         1
94    95          1          1          1         1
95    96          1          1          1         1
96    97          0          0          0         0
97    98          1          1          1         1
98    99          2          2          2         2
99   100          0          0          0         0
100  101          1          1          1         1
101  102          0          0          0         0
102  103          0          0          0         0
103  104          1          1          1         1
104  105          1          1          1         1
105  106          1          1          1         1
106  107          1          1          1         1
107  108          1          0          0         0
108  109          0          0          0         0
109  110          2          2          2         2
110  111          1          1          1         1
111  112          0          0          0         0
112  113          0          0          0         0
113  114          0          0          0         0
114  115          0          0          0         0
115  116          6          6          6         6
116  117          0          0          0         0
117  118          1          1          1         1
118  119          2          2          2         2
119  120          1          1          1         1
120  121          0          0          0         0
121  122          1          1          1         1
122  123          1          1          1         1
123  124          1          1          1         1
124  125          6          6          6         6
125  126          1          1          1         1
126  127          1          1          1         1
127  128          1          1          1         1
128  129          1          1          1         1
129  130          1          1          1         1
130  131          1          1          1         1
131  132          1          1          1         1
132  133          1          1          1         1
133  134          0          0          0         0
134  135          0          0          0         0
135  136          2          2          2         2
136  137          2          2          2         2
137  138          2          2          2         2
138  139          1          1          1         1
139  140          0          0          0         0
140  141          0          0          0         0
141  142          1          1          1         1
142  143          0          0          0         0
143  144          2          2          2         2
144  145          1          1          1         1
145  146          1          1          1         1
146  147          6          6          6         6
147  148          1          1          2         1
148  149          2          2          2         2
149  150          0          0          0         0
150  151          1          1          1         1
151  152          1          1          1         1
152  153          6          6          6         6
153  154          1          1          1         1
154  155          1          1          1         1
155  156          1          1          1         1
156  157          1          1          1         1
157  158          0          0          0         0
158  159          1          1          1         1
159  160          1          1          1         1
160  161          0          0          0         0
161  162          1          1          1         1
162  163          0          0          0         0
163  164          0          0          0         0
164  165          2          2          2         2
165  166          1          1          1         1
166  167          0          0          0         0
167  168          0          0          0         0
168  169          0          0          0         0
169  170          1          1          1         1
170  171          0          0          0         0
171  172          0          0          0         0
172  173          1          1          1         1
173  174          1          1          1         1
174  175          1          1          1         1
175  176          1          1          1         1
176  177          1          1          1         1
177  178          1          1          1         1
178  179          0          0          0         0
179  180          0          0          0         0
180  181          2          2          2         2
181  182          1          1          5         1
182  183          1          1          1         1
183  184          1          1          1         1
184  185          2          2          2         2
185  186          1          1          1         1
186  187          1          1          1         1
187  188          2          2          2         2
188  189          1          1          4         1
189  190          1          1          1         1
190  191          5          5          5         5
191  192          0          0          0         0
192  193          2          0          0         0
193  194          6          6          6         6
194  195          1          1          1         1
195  196          1          1          1         1
196  197          0          0          0         0
197  198          1          1          2         1
198  199          1          1          1         1
199  200          1          1          1         1
200  201          1          1          1         1
201  202          0          0          0         0
202  203          1          1          1         1
203  204          6          6          6         6
204  205          1          1          1         1
205  206          1          1          1         1
206  207          1          1          1         1
207  208          0          0          0         0
208  209          1          1          1         1
209  210         14         14         14        14
210  211          0          0          0         0
211  212          0          0          0         0
212  213          0          0          0         0
213  214          0          0          0         0
214  215          2          2          2         2
215  216          1          1          1         1
216  217          1          1          1         1
217  218          0          0          0         0
218  219          1          1          1         1
219  220          1          1          1         1
220  221          1          1          1         1
221  222          1          1          1         1
222  223          0          0          0         0
223  224          1          1          1         1
224  225          1          1          1         1
225  226          6          6          6         6
226  227          1          1          1         1
227  228          1          1          1         1
228  229          0          0          0         0
229  230          1          1          1         1
230  231          2          2          2         2
231  232          1          1          1         1
232  233          1          1          1         1
233  234          5          5          5         5
234  235          1          1          1         1
235  236          0          0          0         0
236  237          1          1          1         1
237  238          1          1          1         1
238  239          0          0          0         0
239  240          0          0          0         0
240  241          0          0          0         0
241  242          1          1          1         1
242  243          1          1          1         1
243  244          5          2          2         2
244  245          6          6          6         6
245  246          5          5          5         5
246  247          1          1          1         1
247  248          6          6          6         6
248  249          0          0          0         0
249  250          1          1          1         1
250  251          0          0          0         0
251  252          5          5          2         5
252  253          1          1          1         1
253  254          1          1          1         1
254  255          1          1          1         1
255  256          1         15         15        15
256  257          0          0          0         0
257  258          0          0          0         0
258  259          0          0          0         0
259  260          1          1          1         1
260  261          6          6          6         6
261  262          1          1          1         1
262  263          1          1          1         1
263  264          0          0          0         0
264  265          0          0          0         0
265  266          0          0          0         0
266  267          0          0          0         0
267  268          0          0          0         0
268  269          0          0          0         0
269  270          0          0          0         0
270  271          0          0          0         0
271  272          0          0          0         0
272  273          1          1          1         1
273  274          2          2          2         2
274  275          5          5          5         5
275  276          6          6          6         6
276  277          0          0          0         0
277  278          0          0          0         0
278  279          1          2          3         1
279  280          1          1          1         1
280  281          1          1          1         1
281  282          1          1          1         1
282  283          1          1          1         1
283  284          1          1          5         1
284  285          5          5          5         5
285  286          1          1          1         1
286  287          2          2          2         2
287  288          1          1          1         1
288  289          0          0          0         0
289  290          1          1          1         1
290  291          0          0          0         0
291  292          1          1          1         1
292  293          1          1          1         1
293  294          6          6          6         6
294  295          0          0          0         0
295  296          1          5          2         1
296  297          0          0          0         0
297  298          1          1          1         1
298  299         14         14         14        14
299  300          1          5          5         5
300  301          1          1          1         1
301  302          1          1          1         1
302  303          1          1          1         1
303  304          1          1          1         1
304  305          2          1          2         2
305  306          1          1          1         1
306  307          1          1          1         1
307  308          1          1          1         1
308  309          6          6          6         6
309  310          1          1          1         1
310  311          2          2          2         2
311  312          2          1          1         1
312  313          1          1          1         1
313  314          0          0          0         0
314  315          1          1          1         1
315  316          1          1          1         1
316  317          5          5          5         5
317  318          1          1          1         1
318  319          2          2          2         2
319  320          1          1          1         1
320  321          1          1          1         1
321  322          1          1          1         1
322  323          0          0          0         0
323  324          0          0          0         0
324  325          1          1          1         1
325  326          0          0          0         0
326  327          1          1          1         1
327  328          0          0          0         0
328  329          2          1          1         1
329  330          1          1          1         1
330  331          0          0          0         0
331  332          0          0          0         0
332  333          1          1          1         1
333  334          1          1          1         1
334  335          1          1          1         1
335  336          1          1          1         1
336  337          1          1          1         1
337  338          1          1          1         1
338  339          1          1          1         1
339  340          1          1          1         1
340  341          0          5          0         0
341  342          1          1          1         1
342  343          1          1          1         1
343  344          1          1          1         1
344  345          0          0          0         0
345  346          5          5          2         5
346  347          0          0          0         0
347  348          0          0          0         0
348  349          1          1          1         1
349  350          1          1          1         1
350  351          1          1          1         1
351  352          1          1          1         1
352  353          1          2          2         2
353  354          5          5          1         5
354  355          1          1          1         1
355  356          1          1          1         1
356  357          0          0          0         0
357  358          6          6          6         6
358  359          2          2          2         2
359  360          6          6          6         6
360  361          2          2          2         2
361  362          1          1          1         1
362  363          2          2          2         2
363  364          0          0          0         0
364  365          6          6          6         6
365  366          0          0          0         0
366  367          1          1          1         1
367  368          0          0          0         0
368  369          1          1          1         1
369  370          0          0          0         0
370  371          1          1          1         1
371  372          1          1          1         1
372  373          1          1          1         1
373  374          1          1          1         1
374  375          0          0          0         0
375  376          1          1          1         1
376  377          1          1          1         1
377  378          1          1          1         1
378  379          0          0          0         0
379  380          1          1          1         1
380  381          5          5          5         5
381  382          1          1          1         1
382  383          2          2          2         2